language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
before_script: "cd HotkeyList/"
script: "lektor build"
deploy:
  on:
    all_branches: true
  provider: script
  script: "lektor deploy ghpages"
